version: '3.7'
networks:
  overlay-net:
    external: true      
    driver: overlay
services:
  rs:
    image: dockerhub.iudx.io/iudx/rs-depl:2.5.Zookeeper
    volumes:
      - ./secrets/all-verticles-configs/config-depl.json:/usr/share/app/secrets/all-verticles-configs/config.json
    ports:
      - "80:80"
      - "9000:9000"
    networks: 
      - overlay-net
