version: '3.7'

networks:
  overlay-net:
          external: true      
          driver: overlay

services:

  prod:
    image: iudx/rs-depl:latest
    env_file:
      - ./.rs.env
    volumes:
      - ./configs/config-depl.json:/usr/share/app/configs/config.json
      - ./configs/keystore.jks:/usr/share/app/configs/keystore.jks
      - type: volume
        source: rs-volume
        target: /usr/share/app/storage/temp-dir
    ports:
      - "8080:80"
      - "9000:9000"
    restart: on-failure
    networks: 
      - overlay-net
    logging:
         driver: "json-file"
         options:
             max-file: "5"
             max-size: "100m"
    command: bash -c "exec java $$RS_JAVA_OPTS  -Dvertx.logger-delegate-factory-class-name=io.vertx.core.logging.Log4j2LogDelegateFactory -jar ./fatjar.jar  --host $$(hostname) -c configs/config.json"

  dev:
    image: iudx/rs-dev:latest
    env_file:
      - ./.rs.env
    volumes:
      - ./configs/config-depl.json:/usr/share/app/configs/config.json
      - ./configs/keystore.jks:/usr/share/app/configs/keystore.jks
      - type: volume
        source: rs-volume
        target: /usr/share/app/storage/temp-dir
    ports:
      - "8080:8080"
      - "9000:9000"
    restart: on-failure
    networks: 
      - overlay-net
    logging:
         driver: "json-file"
         options:
             max-file: "5"
             max-size: "100m"
    command: bash -c "exec java $$RS_JAVA_OPTS  -Dvertx.logger-delegate-factory-class-name=io.vertx.core.logging.Log4j2LogDelegateFactory -jar ./fatjar.jar  --host $$(hostname) -c configs/config.json"


  zookeeper:
    image: zookeeper:latest
    expose: 
      - "2181"
    networks:
      - overlay-net

volumes:
  rs-volume:

